name: password_hash_plus
version: 3.0.1
description: PBKDF2 password hashing utility.
repository: https://github.com/LiWenHui96/password_hash_plus

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  crypto: ^3.0.0

dev_dependencies:
  test: ^1.16.0
  lints: ^1.0.0
