name: password_hash_plus
version: 4.0.0
description: PBKDF2 password hashing utility. This plugin is a null-safety version of password_hash, you can use it if you need Flutter 2.x and above.
repository: https://github.com/LiWenHui96/password_hash_plus

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  crypto: ^3.0.2

dev_dependencies:
  test: ^1.21.1
  lints: ^2.0.0
